package com.prdv.rdv.common.persistence;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import javax.sql.DataSource;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Garde-fou du démarrage : la conversion ENUM n'a lieu que si Hibernate gère le schéma.
 */
class EnumColumnReconcilerTest {

    private String url;

    @BeforeEach
    void createLegacySchema() throws SQLException {
        url = "jdbc:h2:mem:reconciler-" + UUID.randomUUID() + ";MODE=MySQL;DB_CLOSE_DELAY=-1";
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE audit_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "action ENUM('LOGIN_SUCCESS', 'SOCIAL_LOGIN') NOT NULL)");
            statement.execute("INSERT INTO audit_logs (action) VALUES ('SOCIAL_LOGIN')");
        }
    }

    @AfterEach
    void shutdownDatabase() throws SQLException {
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("SHUTDOWN");
        }
    }

    @Test
    @DisplayName("ddl-auto=update : la colonne ENUM est convertie et la valeur existante conservée")
    void convertsEnumColumnWhenHibernateManagesSchema() throws SQLException {
        new EnumColumnReconciler(dataSource(), "update").afterPropertiesSet();

        assertEquals("CHARACTER VARYING", dataType("AUDIT_LOGS", "ACTION"));
        assertEquals("SOCIAL_LOGIN", queryString("SELECT action FROM audit_logs"));
    }

    @Test
    @DisplayName("ddl-auto=validate ou none : le schéma n'est jamais modifié")
    void leavesSchemaUntouchedWhenNotManagedByHibernate() throws SQLException {
        new EnumColumnReconciler(dataSource(), "validate").afterPropertiesSet();
        new EnumColumnReconciler(dataSource(), "none").afterPropertiesSet();

        assertEquals("ENUM", dataType("AUDIT_LOGS", "ACTION"));
    }

    private DataSource dataSource() {
        return (DataSource) Proxy.newProxyInstance(
                EnumColumnReconcilerTest.class.getClassLoader(),
                new Class<?>[] {DataSource.class},
                (proxy, method, args) -> {
                    if ("getConnection".equals(method.getName()) && (args == null || args.length == 0)) {
                        return DriverManager.getConnection(url, "sa", "");
                    }
                    throw new UnsupportedOperationException(method.getName());
                });
    }

    private String dataType(String table, String column) throws SQLException {
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             PreparedStatement statement = connection.prepareStatement(
                     "SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = ? AND COLUMN_NAME = ?")) {
            statement.setString(1, table);
            statement.setString(2, column);
            try (ResultSet rs = statement.executeQuery()) {
                assertTrue(rs.next(), table + "." + column);
                return rs.getString(1);
            }
        }
    }

    private String queryString(String sql) throws SQLException {
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery(sql)) {
            List<String> values = new ArrayList<>();
            while (rs.next()) {
                values.add(rs.getString(1));
            }
            assertEquals(1, values.size(), sql);
            return values.get(0);
        }
    }
}
